# -*- coding: utf-8 -*-
"""chatboat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Udp0mhvC74O0Yu5apx7qUl1ZzauzCs_G
"""

!pip install cohere google-generativeai

import cohere
from google import generativeai as genai

ckey = ""
gkey = ""

co = cohere.Client(ckey)
genai.configure(api_key=gkey)

from google.colab import files
uploaded_files = files.upload()
pdf_path = list(uploaded_files.keys())[0]
print(f"uploaded files{pdf_path}")

import os

image_folder = "/content/pdf_images"
os.makedirs(image_folder, exist_ok=True)

!pip uninstall fitz -y
!pip install pymupdf

!pip uninstall fitz -y
!pip install pymupdf

!pip uninstall fitz -y
!pip uninstall pymupdf -y
!pip install pymupdf

import os

import fitz
import os

image_folder = "images"
os.makedirs(image_folder, exist_ok=True)

txt_chunks = []
img_chunks = []

doc = fitz.open(pdf_path)

for pnum in range(len(doc)):
    page = doc[pnum]
    txt = page.get_text()

    if txt.strip():
        txt_chunks.append(txt)

    images = page.get_images(full=True)

    for img_ind, img in enumerate(images):
        xref = img[0]
        base_img = doc.extract_image(xref)#Returns a dictionary with image data.

        img_bytes = base_img["image"] #Gets raw image data (binary format).
        ext = base_img["ext"] #Gets file type (like "png", "jpeg").

        img_fn = f"page_{pnum+1}_img{img_ind+1}.{ext}"
        img_path = os.path.join(image_folder, img_fn)

        with open(img_path, "wb") as img_file:
            img_file.write(img_bytes)

        img_chunks.append(img_path)

print(f"Extracted {len(txt_chunks)} text chunks and {len(img_chunks)} images")

#image encoding utis

from PIL import Image
import numpy as np
import base64   #encod bin img data->txt
import io # in mem file stg-file in mem


max_pixel = 1568 * 1568

#resize

def resize_image(pil_image):
  og_w,og_h = pil_image.size
  if og_w * og_h > max_pixel:
    scale_factor = (max_pixel / (og_w * og_h))*0.5
    new_w = int(og_w * scale_factor)
    new_h = int(og_h * scale_factor)
    pil_image.thumbail((new_w, new_h)) #main aspect ratio


#base 64-def base64_from_image(img_path):


def base64_from_image(img_path):
  pil_image = Image.open(img_path).convert("RGB")
  resize_image(pil_image)

  with io.BytesIO() as image_file:
    pil_image.save(image_file, format="PNG")
    image_file.seek(0)
    return base64.b64encode(image_file.read()).decode("utf-8")

pip install chromadb

#chroma d vector db

import chromadb
from chromadb.config import Settings

chroma_client = chromadb.PersistentClient(path="/content/chroma_db")
collection = chroma_client.get_or_create_collection(name="multimodal_collection")

pip install tqdm

import uuid
from tqdm import tqdm

for i,chunk in tqdm(enumerate(txt_chunks), desc="Storing txt"):
    res = co.embed(
        model="embed-multilingual-v3.0",
        input_type="search_document",
        embedding_types=["float"],
        texts=[chunk]
    )

    emb = res.embeddings.float[0]

    collection.add(
        ids=[f"text_{uuid.uuid4()}"],
        documents=[chunk],
        embeddings=[emb],
        metadatas=[{"source": "txt"}]
    )

    #img embeddings

for img_path in tqdm(img_chunks, desc="Storing imgs"):

  base64_img = base64_from_image(img_path)
  api_in = {
    "content": [
        {
            "type": "image",
            "image": base64_img,
            "encoding": "base64"
        }
    ]
}
  res = co.embed(
        model="embed-multilingual-v3.0",
        input_type="search_document",
        embedding_types=["float"],
        texts=[api_in]
    )

  emb = res.embeddings.float[0]

  collection.add(
        ids=[f"img_{uuid.uuid4()}"],
        documents=[img_path],
        embeddings=[emb],
        metadatas=[{"type": "image"}]
    )

#prompt formatting via langchain

!pip install langchain-google-genai

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.messages import HumanMessage
from langchain_core.runnables import RunnablePassthrough
from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash",
                             temperature = 0.3,
                             google_api_key="AIzaSyDEFms5dr_6is_4AMTLWkIAXaEI6PB7H34")

#struc prompt template

prompt_template = ChatPromptTemplate.from_messages([
    ("system", "You are a helpful AI assistant."),
    ("human", "Answer the following question:\n\nQuestion: {question}\n\nContext:\n{context}")
])
chain = (
    RunnablePassthrough()
    | (lambda inputs: {
        "question": inputs["question"],
        "context": inputs["context"]
    })
    | prompt_template
    | llm
    | StrOutputParser()
)

#response generation

def search_and_answer(question,top_k=2):
  #query embedding

  qres = co.embed(
      model="embed-multilingual-v3.0",
      input_type="search_query",
      embedding_types=["float"],
      texts=[question]
  )
  query_emb = qres.embeddings.float[0]

  #pass to chroma tb

  res = collection.query(
      query_embeddings=[query_emb],
      n_results=top_k*2
  )

  top_text,top_images=[],[]

  for doc,meta in zip(res["documents"][0],res["metadatas"][0]):
    if meta["source"] == "txt":
      top_text.append(doc)
    else:
      top_images.append(doc)

  #only take relevant info

  top_texts = top_text[:top_k]
  top_images = top_images[:top_k]


  #prepare context

  context = "\n\n".join(top_texts + [f"[IMAGE: {img}]" for img in top_images])

  response_text = chain.invoke({
      "context": context,
      "question": question
  })

  return response_text,top_images

#final o/p

from IPython.display import display, Image, HTML

question="give me my skills "
answer_txt,res_images=search_and_answer(question)

print("Gemini answer:")
print(answer_txt)

for i in res_images:
  display(Image(url=i))









